package com.ohthedungeon.mythictweak.gui;

import com.ohthedungeon.mythictweak.config.SpawnerConfig;
import java.io.File;
import java.io.IOException;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author shadow_wind
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        String path = "";
        path = path + "OTD_MythicTweak/";
        File dir = new File(path);
        if(!dir.exists()) dir.mkdirs();
        
        String filepath = path + SpawnerConfig.CONFIG_FILE_NAME;
        File file = new File(filepath);
        try {
            SpawnerConfig.loadConfig(file);
            showMessageDialog(null, "Using config file: " + file.getAbsolutePath());
        } catch(IOException ex) {
            showMessageDialog(null, "Error happened while loading " + file.getAbsolutePath());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_edit_level_0 = new javax.swing.JButton();
        label_hint = new javax.swing.JLabel();
        button_edit_level_1 = new javax.swing.JButton();
        button_edit_level_2 = new javax.swing.JButton();
        button_edit_level_3 = new javax.swing.JButton();
        button_edit_level_4 = new javax.swing.JButton();
        button_save = new javax.swing.JButton();
        button_walled = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OTD_MythicTweak");
        setResizable(false);

        button_edit_level_0.setText("Roguelike Dungeon Level 0");
        button_edit_level_0.setToolTipText("y=50~60");
        button_edit_level_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edit_level_0ActionPerformed(evt);
            }
        });

        label_hint.setText(" Hover will show a prompt");

        button_edit_level_1.setText("Roguelike Dungeon Level 1");
        button_edit_level_1.setToolTipText("y=40~50");
        button_edit_level_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edit_level_1ActionPerformed(evt);
            }
        });

        button_edit_level_2.setText("Roguelike Dungeon Level 2");
        button_edit_level_2.setToolTipText("y=30~40");
        button_edit_level_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edit_level_2ActionPerformed(evt);
            }
        });

        button_edit_level_3.setText("Roguelike Dungeon Level 3");
        button_edit_level_3.setToolTipText("y=20~30");
        button_edit_level_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edit_level_3ActionPerformed(evt);
            }
        });

        button_edit_level_4.setText("Roguelike Dungeon Level 4");
        button_edit_level_4.setToolTipText("y=10~20");
        button_edit_level_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_edit_level_4ActionPerformed(evt);
            }
        });

        button_save.setText("Save Config");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        button_walled.setText("How to Prevent Mob Stuck in Walls");
        button_walled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_walledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_edit_level_0, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_edit_level_1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_edit_level_2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_edit_level_3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_edit_level_4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_walled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(label_hint)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_edit_level_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(button_edit_level_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(button_edit_level_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(button_edit_level_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(button_edit_level_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(button_walled, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(label_hint)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_edit_level_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edit_level_2ActionPerformed
        // TODO add your handling code here:
        DungeonLevelEditor d = new DungeonLevelEditor(2);
        d.setVisible(true);
    }//GEN-LAST:event_button_edit_level_2ActionPerformed

    private void button_edit_level_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edit_level_3ActionPerformed
        // TODO add your handling code here:
        DungeonLevelEditor d = new DungeonLevelEditor(3);
        d.setVisible(true);
    }//GEN-LAST:event_button_edit_level_3ActionPerformed

    private void button_edit_level_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edit_level_4ActionPerformed
        // TODO add your handling code here:
        DungeonLevelEditor d = new DungeonLevelEditor(4);
        d.setVisible(true);
    }//GEN-LAST:event_button_edit_level_4ActionPerformed

    private void button_edit_level_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edit_level_0ActionPerformed
        // TODO add your handling code here:
        DungeonLevelEditor d = new DungeonLevelEditor(0);
        d.setVisible(true);
    }//GEN-LAST:event_button_edit_level_0ActionPerformed

    private void button_edit_level_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_edit_level_1ActionPerformed
        // TODO add your handling code here:
        DungeonLevelEditor d = new DungeonLevelEditor(1);
        d.setVisible(true);
    }//GEN-LAST:event_button_edit_level_1ActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        // TODO add your handling code here:
//        String path = MainJFrame.class.getProtectionDomain().getCodeSource().getLocation().getPath();
        String path = "";
        path = path + "OTD_MythicTweak/";
        File dir = new File(path);
        if(!dir.exists()) dir.mkdirs();
        
        File file = new File(path + SpawnerConfig.CONFIG_FILE_NAME);
        try {
            SpawnerConfig.saveConfig(file);

            showMessageDialog(null, "All options is saved to " + file.getAbsolutePath() + "\n" + 
                    "\n" +
                    "- You may need to upload spawner_config.json to you server, 'plugins/otd_mythictweak/spawner_config.json'\n" +
                    "- You need to run '/otd_mt reload' if your server is already running"
            );
        } catch(IOException ex) {
            showMessageDialog(null, "Error happened while saving " + file.getAbsolutePath());
        }
    }//GEN-LAST:event_button_saveActionPerformed

    private void button_walledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_walledActionPerformed
        // TODO add your handling code here:
        MobWall mw = new MobWall();
        mw.setVisible(true);
    }//GEN-LAST:event_button_walledActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_edit_level_0;
    private javax.swing.JButton button_edit_level_1;
    private javax.swing.JButton button_edit_level_2;
    private javax.swing.JButton button_edit_level_3;
    private javax.swing.JButton button_edit_level_4;
    private javax.swing.JButton button_save;
    private javax.swing.JButton button_walled;
    private javax.swing.JLabel label_hint;
    // End of variables declaration//GEN-END:variables
}
