package com.ohthedungeon.mythictweak.gui;

import javax.swing.JFrame;

/**
 *
 * @author shadow_wind
 */
public class MobWall extends javax.swing.JFrame {

    /**
     * Creates new form MobWall
     */
    public MobWall() {
        initComponents();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        jTextArea.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.setText("Create pw.yml in `plugins\\MythicMobs\\Skills\\\nContent of pw.yml:\n\nPreventWalled:\n  Conditions:\n  - inblock{b=AIR} false\n  Skills:\n  - remove @Self\n\n\nEdit your mythicmobs' yml in`plugins\\MythicMobs\\Mobs\\'\n\nAdd the following skills:\n  Skills:\n  - skill{s=PreventWalled} @Self ~onSpawn\n\nExample(For SkeletalKnight in ExampleMobs.yml):\n\nSkeletalKnight:\n  Type: WITHER_SKELETON\n  Display: '&aSkeletal Knight'\n  Health: 40\n  Damage: 8\n  Equipment:\n  - IRON_HELMET HEAD\n  - IRON_CHESTPLATE CHEST\n  - IRON_LEGGINGS LEGS\n  - IRON_BOOTS FEET\n  - IRON_SWORD HAND\n  - SHIELD OFFHAND\n  Drops:\n  - GOLD_NUGGET{display=\"Gold Coin\"} 1to2 0.5\n  LevelModifiers:\n  - health 5\n  - damage 0.5\n  Options:\n    MovementSpeed: 0.1\n  Skills:\n  - skill{s=PreventWalled} @Self ~onSpawn");
        jScrollPane1.setViewportView(jTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MobWall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MobWall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MobWall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MobWall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobWall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
